name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, pdo_sqlite, sqlite3
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: App key & .env.testing
        run: |
          cp .env.example .env.testing
          php -r "file_put_contents('.env.testing', preg_replace('/^DB_CONNECTION=.*/m','DB_CONNECTION=sqlite', file_get_contents('.env.testing')));"
          echo "DB_DATABASE=:memory:" >> .env.testing
          echo "CACHE_DRIVER=array" >> .env.testing
          echo "SESSION_DRIVER=array" >> .env.testing
          echo "QUEUE_CONNECTION=sync" >> .env.testing
          echo "SANCTUM_STATEFUL_DOMAINS=" >> .env.testing
          echo "SESSION_DOMAIN=localhost" >> .env.testing
          php artisan key:generate --env=testing

      - name: Optimize (optional)
        run: |
          php artisan config:clear --env=testing
          php artisan route:clear --env=testing
          php artisan view:clear --env=testing

      - name: Run tests
        env:
          APP_ENV: testing
          APP_KEY: base64:dummyKeyWillBeOverwritten=
        run: php artisan test --env=testing -q
