name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, pdo_sqlite, sqlite3
          coverage: none

      - name: Cache Composer (vendor)
        uses: actions/cache@v4
        with:
          path: backend/vendor
          key: composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: App key & .env.testing
        run: |
          cp .env.example .env.testing
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env.testing
          printf '%s\n' \
            'DB_DATABASE=:memory:' \
            'CACHE_DRIVER=array' \
            'SESSION_DRIVER=array' \
            'QUEUE_CONNECTION=sync' \
            'SANCTUM_STATEFUL_DOMAINS=' \
            'SESSION_DOMAIN=localhost' \
            >> .env.testing
          php artisan key:generate --env=testing

      - name: Optimize (optional)
        run: |
          php artisan config:clear --env=testing
          php artisan route:clear --env=testing
          php artisan view:clear --env=testing

      - name: Run tests
        env:
          APP_ENV: testing
        run: php artisan test --env=testing -q
