name: CI

on:
  push:
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, pdo_sqlite, sqlite3
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: backend/vendor
          key: composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: composer-

      - name: Install backend dependencies
        working-directory: ./backend
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: App key & .env.testing
        working-directory: ./backend
        run: |
          cp .env.example .env.testing
          php -r "file_put_contents('.env.testing', preg_replace('/^DB_CONNECTION=.*/m','DB_CONNECTION=sqlite', file_get_contents('.env.testing')));"
          echo "DB_DATABASE=:memory:" >> .env.testing
          echo "CACHE_DRIVER=array" >> .env.testing
          echo "SESSION_DRIVER=array" >> .env.testing
          echo "QUEUE_CONNECTION=sync" >> .env.testing
          echo "SANCTUM_STATEFUL_DOMAINS=" >> .env.testing
          echo "SESSION_DOMAIN=localhost" >> .env.testing
          php artisan key:generate --env=testing

      - name: Optimize (optional)
        working-directory: ./backend
        run: |
          php artisan config:clear --env=testing
          php artisan route:clear --env=testing
          php artisan view:clear --env=testing

      - name: Run backend tests
        working-directory: ./backend
        env:
          APP_ENV: testing
          APP_KEY: base64:dummyKeyWillBeOverwritten=
        run: php artisan test --env=testing

  frontend-build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend build
        working-directory: ./frontend
        run: npm run build

      # Só roda "npm test" se existir script "test" no package.json
      - name: Run frontend tests (if present)
        working-directory: ./frontend
        run: |
          if node -e "process.exit(!!(require('./package.json').scripts && require('./package.json').scripts.test) ? 0 : 1)"; then
            echo "Found test script in package.json. Running: npm test"
            npm test
          else
            echo "No \"test\" script in package.json. Skipping frontend tests."
          fi
